/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI2;

import SymbolTable.SymbolTable;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;
import SymbolTable.Symbol;

/**
 *
 * @author Alberth
 */
public class Detalles extends javax.swing.JFrame {

    /**
     * Creates new form Detalles
     */
    public Detalles() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTabbedPane_Principa = new javax.swing.JTabbedPane();
        jPanel_Errors = new javax.swing.JPanel();
        jScrollPane_Errors = new javax.swing.JScrollPane();
        jTextArea_Errors = new javax.swing.JTextArea();
        jPanel_AST = new javax.swing.JPanel();
        jScrollPane_AST = new javax.swing.JScrollPane();
        jTextArea_AST = new javax.swing.JTextArea();
        jPanel_IR = new javax.swing.JPanel();
        jScrollPane_IR = new javax.swing.JScrollPane();
        jTextArea_IR = new javax.swing.JTextArea();
        jPanel_LLVM = new javax.swing.JPanel();
        jScrollPaneLLVM = new javax.swing.JScrollPane();
        jTextArea_LLVM = new javax.swing.JTextArea();
        jPanel_SymbolTable = new javax.swing.JPanel();
        jLabel_SymbolTable = new javax.swing.JLabel();
        jScrollPane_SymbolTable = new javax.swing.JScrollPane();
        jTable_SymbolTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea_Errors.setColumns(20);
        jTextArea_Errors.setRows(5);
        jScrollPane_Errors.setViewportView(jTextArea_Errors);

        javax.swing.GroupLayout jPanel_ErrorsLayout = new javax.swing.GroupLayout(jPanel_Errors);
        jPanel_Errors.setLayout(jPanel_ErrorsLayout);
        jPanel_ErrorsLayout.setHorizontalGroup(
                jPanel_ErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ErrorsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_Errors, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel_ErrorsLayout.setVerticalGroup(
                jPanel_ErrorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ErrorsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_Errors, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane_Principa.addTab("Error Semantico", jPanel_Errors);

        jTextArea_AST.setColumns(20);
        jTextArea_AST.setRows(5);
        jScrollPane_AST.setViewportView(jTextArea_AST);

        javax.swing.GroupLayout jPanel_ASTLayout = new javax.swing.GroupLayout(jPanel_AST);
        jPanel_AST.setLayout(jPanel_ASTLayout);
        jPanel_ASTLayout.setHorizontalGroup(
                jPanel_ASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ASTLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_AST, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel_ASTLayout.setVerticalGroup(
                jPanel_ASTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_ASTLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane_AST, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jTabbedPane_Principa.addTab("AST", jPanel_AST);

        jTextArea_IR.setColumns(20);
        jTextArea_IR.setRows(5);
        jScrollPane_IR.setViewportView(jTextArea_IR);

        javax.swing.GroupLayout jPanel_IRLayout = new javax.swing.GroupLayout(jPanel_IR);
        jPanel_IR.setLayout(jPanel_IRLayout);
        jPanel_IRLayout.setHorizontalGroup(
                jPanel_IRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_IRLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_IR, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel_IRLayout.setVerticalGroup(
                jPanel_IRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_IRLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane_IR, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane_Principa.addTab("IR", jPanel_IR);

        jTextArea_LLVM.setColumns(20);
        jTextArea_LLVM.setRows(5);
        jScrollPaneLLVM.setViewportView(jTextArea_LLVM);

        javax.swing.GroupLayout jPanel_LLVMLayout = new javax.swing.GroupLayout(jPanel_LLVM);
        jPanel_LLVM.setLayout(jPanel_LLVMLayout);
        jPanel_LLVMLayout.setHorizontalGroup(
                jPanel_LLVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_LLVMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPaneLLVM, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel_LLVMLayout.setVerticalGroup(
                jPanel_LLVMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_LLVMLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPaneLLVM, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane_Principa.addTab("LLVM", jPanel_LLVM);

        jLabel_SymbolTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_SymbolTable.setText("Tabla de Simbolos");

        jTable_SymbolTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null},
                        {null, null, null},
                        {null, null, null},
                        {null, null, null}
                },
                new String [] {
                        "Identificador", "Tipo", "Scope"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane_SymbolTable.setViewportView(jTable_SymbolTable);

        javax.swing.GroupLayout jPanel_SymbolTableLayout = new javax.swing.GroupLayout(jPanel_SymbolTable);
        jPanel_SymbolTable.setLayout(jPanel_SymbolTableLayout);
        jPanel_SymbolTableLayout.setHorizontalGroup(
                jPanel_SymbolTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_SymbolTableLayout.createSequentialGroup()
                                .addGap(364, 364, 364)
                                .addComponent(jLabel_SymbolTable, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_SymbolTableLayout.createSequentialGroup()
                                .addContainerGap(110, Short.MAX_VALUE)
                                .addComponent(jScrollPane_SymbolTable, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
        );
        jPanel_SymbolTableLayout.setVerticalGroup(
                jPanel_SymbolTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_SymbolTableLayout.createSequentialGroup()
                                .addContainerGap(35, Short.MAX_VALUE)
                                .addComponent(jLabel_SymbolTable)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_SymbolTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );

        jTabbedPane_Principa.addTab("Tabla de Simbolos", jPanel_SymbolTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTabbedPane_Principa, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTabbedPane_Principa, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JLabel jLabel_SymbolTable;
    public javax.swing.JPanel jPanel_AST;
    public javax.swing.JPanel jPanel_Errors;
    public javax.swing.JPanel jPanel_IR;
    public javax.swing.JPanel jPanel_LLVM;
    public javax.swing.JPanel jPanel_SymbolTable;
    public javax.swing.JScrollPane jScrollPaneLLVM;
    public javax.swing.JScrollPane jScrollPane_AST;
    public javax.swing.JScrollPane jScrollPane_Errors;
    public javax.swing.JScrollPane jScrollPane_IR;
    public javax.swing.JScrollPane jScrollPane_SymbolTable;
    public javax.swing.JTabbedPane jTabbedPane_Principa;
    public javax.swing.JTable jTable_SymbolTable;
    public javax.swing.JTextArea jTextArea_AST;
    public javax.swing.JTextArea jTextArea_Errors;
    public javax.swing.JTextArea jTextArea_IR;
    public javax.swing.JTextArea jTextArea_LLVM;
    // End of variables declaration
}
